spring:
  datasource:
    url: jdbc:mysql://monorail.proxy.rlwy.net:15114/railway
    username: root
    password: wQTExgAUDkSVnnsWhKiCwydwlBNgByHU
    driver-class-name: com.mysql.cj.jdbc.Driver

# JPA Configuration
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: false
      properties:
        hibernate:
          format_sql: false
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8Dialect