#spring.application.name=Spring_Jwt
#
##Sql driver connection
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.datasource.url=jdbc:mysql://localhost:3306/spring_jwt?createTableIfNotExists=true
#spring.datasource.username=root
#spring.datasource.password=#@incorrect
#
## to show the query in the terminal,whenever our application runs
#spring.jpa.show-sql=true
#
## auto update the tables, whenever we create the model classes
#spring.jpa.hibernate.ddl-auto=update
#
#server.port=9091











spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_jwt
    username: root
    password: "#@incorrect"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 9001
